repository: NewValleyChurch/documentation-theme-jekyll

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: New Valley Church
site_title: New Valley Church Docs
company_name: New Valley Church
title: New Valley Resources
source: /var/www/newvalleyresources
destination: /home/newvalleyresources/public_html

author:
  jon_griffith:
    name: Jon Griffith
    email: jon@jongriffith.com
    web: http://www.jongriffith.com


# this appears in the footer

github_editme_path:
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

# gitlab_editme_path: tomjoht/documentation-theme-jekyll/blob/gh-pages/
# if you're using GitLab, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

disqus_shortname: newvalleychurchpages
# if you're using disqus for comments, add the shortname here. if not, leave this value blank.

google_analytics: UA-112761625-1
# if you have google-analytics ID, put it in. if not, edit this value to blank.

host: 192.168.1.100
# the preview server used. Leave as is.

port: 4004
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - .idea/
  - .gitignore
  - ._*
# these are the files and directories that jekyll will exclude from the build

feedback_subject_line: New Valley Resources Site

feedback_email: jon@jongriffith.com
# used as a contact email for the Feedback link in the top navigation bar

# feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_text: "Need help?"
# if you uncomment the previous line, it changes the Feedback text

# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

collections:
  tooltips:
    output: false
# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: main_sidebar
      topnav: topnav
      image_folder: images
      document_folder: documents

  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true
      image_folder: images
      document_folder: documents

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true      
      sidebar: main_sidebar
      topnav: topnav
      image_folder: images
      document_folder: documents

  -
    scope:
      path: ""
      type: "diagrams"
    values:
      layout: "page"
      permalink: ""
      comments: true
      search: true
      sidebar: main_sidebar
      topnav: topnav
      image_folder: images
      document_folder: documents

# these are defaults used for the frontmatter for these file types

sidebars:
- main_sidebar

description: "Intended as a documentation theme based on Jekyll for technical writers documenting software and other technical products, this theme has all the elements you would need to handle multiple products with both multi-level sidebar navigation, tags, and other documentation features."
# the description is used in the feed.xml file

# needed for sitemap.xml file only

url: https://newvalleyresources.com
baseurl: ""
documenturl: https://newvalleyresources.com/documents/

plugins:
  - jekyll-admin
  - jekyll-last-modified-at
